/**
 * ============================================================
 * Translations for the Interface, add as many as you want!
 * ============================================================
 **/

var strings = {

	"English": {
		"Back": "Back",
		"Start": "Start",
		"Load": "Load",
		"Loading": "Loading",
		"LoadingMessage": "Wait while the assets are loaded.",
		"Save": "Save",
		"Close": "Close",
		"Language": "Language",
		"Settings": "Settings",
		"Audio": "Audio",
		"Voice": "Voice Volume",
		"Music": "Music Volume",
		"Sound": "Sound Volume",
		"Help": "Help",
		"AdvanceHelp": "To advance through the game, press the space key or click.",
		"QuickButtons": "Quick Menu Buttons",
		"BackButton": "Back.",
		"HideButton": "Hide Text.",
		"SaveButon": "Open the Save Screen.",
		"LoadButton": "Open the Load Screen.",
		"SettingsButton": "Open the Settings Screen.",
		"QuitButton": "Quit Game.",
		"Confirm": "Do you want to quit?",
		"LoadSlots": "Saved Games",
		"LoadAutoSaveSlots": "Auto Saved Games"
	},

	"Español": {
		"Back": "Atrás",
		"Start": "Comenzar",
		"Load": "Cargar",
		"Loading": "Cargando",
		"LoadingMessage": "Espere mientras se cargan los archivos.",
		"Save": "Guardar",
		"Close": "Cerrar",
		"Language": "Lenguaje",
		"Settings": "Configuración",
		"Audio": "Audio",
		"Voice": "Volumen de la Voz",
		"Music": "Volumen de la Música",
		"Sound": "Volumen de los Sonidos",
		"Help": "Ayuda",
		"AdvanceHelp": "Para avanzar en el juego, presiona espacio o haz click.",
		"QuickButtons": "Botones del Menú Rápido",
		"BackButton": "Atrás.",
		"HideButton": "Esconder el Texto.",
		"SaveButon": "Abrir la Pantalla de Guardar.",
		"LoadButton": "Abrir la Pantalla de Cargar.",
		"SettingsButton": "Abrir la Pantalla de Configuración.",
		"QuitButton": "Salir del Juego.",
		"Confirm": "¿Deseas salir?",
		"LoadSlots": "Juegos Guardados",
		"LoadAutoSaveSlots": "Juegos Guardados Automaticamente"
	},

	"Français": {
		"Back": "Retourner",
		"Start": "Démarrer",
		"Load": "Charger",
		"Loading": "Charge",
		"LoadingMessage": "Attendez pendant que les fichiers sont chargés.",
		"Save": "Sauvegarder",
		"Close": "Fermer",
		"Language": "Langue",
		"Settings": "Préférences",
		"Audio": "Audio",
		"Voice": "Volume de la Voix",
		"Music": "Volume de la Musique",
		"Sound": "Volume des Sons",
		"Help": "Aide",
		"AdvanceHelp": "Pour avancer dans le jeu, appuyez sur la touche espace ou cliquez sur.",
		"QuickButtons": "Boutons du Menu Rapide",
		"BackButton": "Retourner.",
		"HideButton": "Cacher le Texte.",
		"SaveButon": "Ouvrir l'écran de Sauvegarde.",
		"LoadButton": "Ouvrir l'écran de Chargement.",
		"SettingsButton": "Ouvrir l'écran des Préférences.",
		"QuitButton": "Quitter le Jeu.",
		"Confirm": "Voulez-vous vraiment quitter?",
		"LoadSlots": "Jeux Sauvegardés",
		"LoadAutoSaveSlots": "Jeux Sauvegardés Automatiquement"
	},

	"日本語": {
		"Back": "巻き戻し",
		"Start": "スタート",
		"Load": "ロード",
		"Loading": "読み込み中",
		"LoadingMessage": "ファイルがロードされるのを待ちます。",
		"Save": "セーブ",
		"Close": "閉めて",
		"Language": "言語",
		"Settings": "環境設定",
		"Audio": "オーディオ",
		"Voice": "ボイスの音量",
		"Music": "音楽の音量",
		"Sound": "効果音の音量",
		"Help": "ヘルプ",
		"AdvanceHelp": "ゲームを進めるためには、スペースキーを押すかクリックします。",
		"QuickButtons": "クイックメニューボタン",
		"BackButton": "巻き戻し",
		"HideButton": "テキストを隠します。",
		"SaveButon": "保存画面を開きます。",
		"LoadButton": "ロード画面を開きます。",
		"SettingsButton": "設定画面を開きます。.",
		"QuitButton": "ゲームを終了します。",
		"Confirm": "終了しますか？",
		"LoadSlots": "保存されたゲーム",
		"LoadAutoSaveSlots": "自動的に保存されたゲーム"
	}
}
