name: Build Core

on:
  push:
    branches:
      - develop
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/**'
      - '!cypress/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Build Core
        run: bun run build
