name: Run Tests

on:
  push:
    branches:
      - develop
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.css'
      - '**/test.yml'
      - '!dist/**'
  pull_request:
    branches:
      - develop
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
          build: bun run build
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
